[build]
builder = "NIXPACKS"
buildCommand = "npm ci && npm run build && ls .next/standalone/server.js"

[deploy]
startCommand = "node .next/standalone/server.js"
healthcheckPath = "/"
healthcheckTimeout = 60
restartPolicyType = "on_failure"
