// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: ent.sql

package sqlcdb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const clearENTAnswersForQuestion = `-- name: ClearENTAnswersForQuestion :exec

DELETE FROM ent_selected_options WHERE attempt_id = $1 AND question_id = $2
`

type ClearENTAnswersForQuestionParams struct {
	AttemptID  int32 `json:"attempt_id"`
	QuestionID int32 `json:"question_id"`
}

// ── ent_selected_options ──────────────────────────────────────────────────────
func (q *Queries) ClearENTAnswersForQuestion(ctx context.Context, arg ClearENTAnswersForQuestionParams) error {
	_, err := q.db.Exec(ctx, clearENTAnswersForQuestion, arg.AttemptID, arg.QuestionID)
	return err
}

const createENTAttempt = `-- name: CreateENTAttempt :one

INSERT INTO ent_attempts (user_id, subject3_id, subject4_id)
VALUES ($1, $2, $3)
RETURNING id, user_id, subject3_id, subject4_id, started_at, finished_at, score1, score2, score3, score4
`

type CreateENTAttemptParams struct {
	UserID     int32       `json:"user_id"`
	Subject3ID pgtype.Int4 `json:"subject3_id"`
	Subject4ID pgtype.Int4 `json:"subject4_id"`
}

// ── ent_attempts ─────────────────────────────────────────────────────────────
func (q *Queries) CreateENTAttempt(ctx context.Context, arg CreateENTAttemptParams) (EntAttempt, error) {
	row := q.db.QueryRow(ctx, createENTAttempt, arg.UserID, arg.Subject3ID, arg.Subject4ID)
	var i EntAttempt
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Subject3ID,
		&i.Subject4ID,
		&i.StartedAt,
		&i.FinishedAt,
		&i.Score1,
		&i.Score2,
		&i.Score3,
		&i.Score4,
	)
	return i, err
}

const finishENTAttempt = `-- name: FinishENTAttempt :one
UPDATE ent_attempts
SET finished_at = NOW(), score1 = $2, score2 = $3, score3 = $4, score4 = $5
WHERE id = $1
RETURNING id, user_id, subject3_id, subject4_id, started_at, finished_at, score1, score2, score3, score4
`

type FinishENTAttemptParams struct {
	ID     int32       `json:"id"`
	Score1 pgtype.Int2 `json:"score1"`
	Score2 pgtype.Int2 `json:"score2"`
	Score3 pgtype.Int2 `json:"score3"`
	Score4 pgtype.Int2 `json:"score4"`
}

func (q *Queries) FinishENTAttempt(ctx context.Context, arg FinishENTAttemptParams) (EntAttempt, error) {
	row := q.db.QueryRow(ctx, finishENTAttempt,
		arg.ID,
		arg.Score1,
		arg.Score2,
		arg.Score3,
		arg.Score4,
	)
	var i EntAttempt
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Subject3ID,
		&i.Subject4ID,
		&i.StartedAt,
		&i.FinishedAt,
		&i.Score1,
		&i.Score2,
		&i.Score3,
		&i.Score4,
	)
	return i, err
}

const getENTAttemptByID = `-- name: GetENTAttemptByID :one
SELECT id, user_id, subject3_id, subject4_id, started_at, finished_at, score1, score2, score3, score4 FROM ent_attempts WHERE id = $1
`

func (q *Queries) GetENTAttemptByID(ctx context.Context, id int32) (EntAttempt, error) {
	row := q.db.QueryRow(ctx, getENTAttemptByID, id)
	var i EntAttempt
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Subject3ID,
		&i.Subject4ID,
		&i.StartedAt,
		&i.FinishedAt,
		&i.Score1,
		&i.Score2,
		&i.Score3,
		&i.Score4,
	)
	return i, err
}

const getENTAttemptQuestions = `-- name: GetENTAttemptQuestions :many
SELECT attempt_id, question_id, slot, order_num FROM ent_attempt_questions WHERE attempt_id = $1 ORDER BY slot, order_num
`

func (q *Queries) GetENTAttemptQuestions(ctx context.Context, attemptID int32) ([]EntAttemptQuestion, error) {
	rows, err := q.db.Query(ctx, getENTAttemptQuestions, attemptID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []EntAttemptQuestion{}
	for rows.Next() {
		var i EntAttemptQuestion
		if err := rows.Scan(
			&i.AttemptID,
			&i.QuestionID,
			&i.Slot,
			&i.OrderNum,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getENTSelectedOptions = `-- name: GetENTSelectedOptions :many
SELECT attempt_id, question_id, option_id FROM ent_selected_options WHERE attempt_id = $1
`

func (q *Queries) GetENTSelectedOptions(ctx context.Context, attemptID int32) ([]EntSelectedOption, error) {
	rows, err := q.db.Query(ctx, getENTSelectedOptions, attemptID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []EntSelectedOption{}
	for rows.Next() {
		var i EntSelectedOption
		if err := rows.Scan(&i.AttemptID, &i.QuestionID, &i.OptionID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getMyENTAttempts = `-- name: GetMyENTAttempts :many
SELECT id, user_id, subject3_id, subject4_id, started_at, finished_at, score1, score2, score3, score4 FROM ent_attempts WHERE user_id = $1 ORDER BY started_at DESC
`

func (q *Queries) GetMyENTAttempts(ctx context.Context, userID int32) ([]EntAttempt, error) {
	rows, err := q.db.Query(ctx, getMyENTAttempts, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []EntAttempt{}
	for rows.Next() {
		var i EntAttempt
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Subject3ID,
			&i.Subject4ID,
			&i.StartedAt,
			&i.FinishedAt,
			&i.Score1,
			&i.Score2,
			&i.Score3,
			&i.Score4,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertENTQuestion = `-- name: InsertENTQuestion :exec

INSERT INTO ent_attempt_questions (attempt_id, question_id, slot, order_num)
VALUES ($1, $2, $3, $4)
`

type InsertENTQuestionParams struct {
	AttemptID  int32 `json:"attempt_id"`
	QuestionID int32 `json:"question_id"`
	Slot       int16 `json:"slot"`
	OrderNum   int16 `json:"order_num"`
}

// ── ent_attempt_questions ─────────────────────────────────────────────────────
func (q *Queries) InsertENTQuestion(ctx context.Context, arg InsertENTQuestionParams) error {
	_, err := q.db.Exec(ctx, insertENTQuestion,
		arg.AttemptID,
		arg.QuestionID,
		arg.Slot,
		arg.OrderNum,
	)
	return err
}

const insertENTSelectedOption = `-- name: InsertENTSelectedOption :exec
INSERT INTO ent_selected_options (attempt_id, question_id, option_id)
VALUES ($1, $2, $3)
ON CONFLICT DO NOTHING
`

type InsertENTSelectedOptionParams struct {
	AttemptID  int32 `json:"attempt_id"`
	QuestionID int32 `json:"question_id"`
	OptionID   int32 `json:"option_id"`
}

func (q *Queries) InsertENTSelectedOption(ctx context.Context, arg InsertENTSelectedOptionParams) error {
	_, err := q.db.Exec(ctx, insertENTSelectedOption, arg.AttemptID, arg.QuestionID, arg.OptionID)
	return err
}
