// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: groups.sql

package sqlcdb

import (
	"context"
)

const addStudentToGroup = `-- name: AddStudentToGroup :one
INSERT INTO user_groups (user_id, group_id)
VALUES ($1, $2)
RETURNING id, user_id, group_id, joined_at
`

type AddStudentToGroupParams struct {
	UserID  int32 `json:"user_id"`
	GroupID int32 `json:"group_id"`
}

func (q *Queries) AddStudentToGroup(ctx context.Context, arg AddStudentToGroupParams) (UserGroup, error) {
	row := q.db.QueryRow(ctx, addStudentToGroup, arg.UserID, arg.GroupID)
	var i UserGroup
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.GroupID,
		&i.JoinedAt,
	)
	return i, err
}

const countUserGroups = `-- name: CountUserGroups :one
SELECT COUNT(*) FROM user_groups WHERE user_id = $1
`

func (q *Queries) CountUserGroups(ctx context.Context, userID int32) (int64, error) {
	row := q.db.QueryRow(ctx, countUserGroups, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createGroup = `-- name: CreateGroup :one
INSERT INTO groups (name, city, school, teacher_id, invite_code)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, name, city, school, teacher_id, created_at, updated_at, invite_code
`

type CreateGroupParams struct {
	Name       string `json:"name"`
	City       string `json:"city"`
	School     string `json:"school"`
	TeacherID  int32  `json:"teacher_id"`
	InviteCode string `json:"invite_code"`
}

func (q *Queries) CreateGroup(ctx context.Context, arg CreateGroupParams) (Group, error) {
	row := q.db.QueryRow(ctx, createGroup,
		arg.Name,
		arg.City,
		arg.School,
		arg.TeacherID,
		arg.InviteCode,
	)
	var i Group
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.City,
		&i.School,
		&i.TeacherID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.InviteCode,
	)
	return i, err
}

const getGroupByCode = `-- name: GetGroupByCode :one
SELECT id, name, city, school, teacher_id, created_at, updated_at, invite_code FROM groups WHERE invite_code = $1
`

func (q *Queries) GetGroupByCode(ctx context.Context, inviteCode string) (Group, error) {
	row := q.db.QueryRow(ctx, getGroupByCode, inviteCode)
	var i Group
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.City,
		&i.School,
		&i.TeacherID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.InviteCode,
	)
	return i, err
}

const getGroupByID = `-- name: GetGroupByID :one
SELECT id, name, city, school, teacher_id, created_at, updated_at, invite_code FROM groups WHERE id = $1
`

func (q *Queries) GetGroupByID(ctx context.Context, id int32) (Group, error) {
	row := q.db.QueryRow(ctx, getGroupByID, id)
	var i Group
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.City,
		&i.School,
		&i.TeacherID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.InviteCode,
	)
	return i, err
}

const getGroupByIdentity = `-- name: GetGroupByIdentity :one
SELECT id, name, city, school, teacher_id, created_at, updated_at, invite_code FROM groups WHERE city = $1 AND school = $2 AND name = $3
`

type GetGroupByIdentityParams struct {
	City   string `json:"city"`
	School string `json:"school"`
	Name   string `json:"name"`
}

func (q *Queries) GetGroupByIdentity(ctx context.Context, arg GetGroupByIdentityParams) (Group, error) {
	row := q.db.QueryRow(ctx, getGroupByIdentity, arg.City, arg.School, arg.Name)
	var i Group
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.City,
		&i.School,
		&i.TeacherID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.InviteCode,
	)
	return i, err
}

const getGroupsByTeacher = `-- name: GetGroupsByTeacher :many
SELECT id, name, city, school, teacher_id, created_at, updated_at, invite_code FROM groups WHERE teacher_id = $1 ORDER BY created_at DESC
`

func (q *Queries) GetGroupsByTeacher(ctx context.Context, teacherID int32) ([]Group, error) {
	rows, err := q.db.Query(ctx, getGroupsByTeacher, teacherID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Group{}
	for rows.Next() {
		var i Group
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.City,
			&i.School,
			&i.TeacherID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.InviteCode,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getGroupsByUser = `-- name: GetGroupsByUser :many
SELECT g.id, g.name, g.city, g.school, g.teacher_id, g.created_at, g.updated_at, g.invite_code FROM groups g
JOIN user_groups ug ON ug.group_id = g.id
WHERE ug.user_id = $1
ORDER BY ug.joined_at
`

func (q *Queries) GetGroupsByUser(ctx context.Context, userID int32) ([]Group, error) {
	rows, err := q.db.Query(ctx, getGroupsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Group{}
	for rows.Next() {
		var i Group
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.City,
			&i.School,
			&i.TeacherID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.InviteCode,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getStudentsByGroup = `-- name: GetStudentsByGroup :many
SELECT u.id, u.phone, u.first_name, u.last_name, u.middle_name, u.city, u.role_id, u.password_hash, u.telegram_chat_id, u.is_banned, u.created_at, u.updated_at, u.profile_subject1, u.profile_subject2 FROM users u
JOIN user_groups ug ON ug.user_id = u.id
WHERE ug.group_id = $1
ORDER BY u.last_name, u.first_name
`

func (q *Queries) GetStudentsByGroup(ctx context.Context, groupID int32) ([]User, error) {
	rows, err := q.db.Query(ctx, getStudentsByGroup, groupID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []User{}
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Phone,
			&i.FirstName,
			&i.LastName,
			&i.MiddleName,
			&i.City,
			&i.RoleID,
			&i.PasswordHash,
			&i.TelegramChatID,
			&i.IsBanned,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ProfileSubject1,
			&i.ProfileSubject2,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeStudentFromGroup = `-- name: RemoveStudentFromGroup :exec
DELETE FROM user_groups WHERE user_id = $1 AND group_id = $2
`

type RemoveStudentFromGroupParams struct {
	UserID  int32 `json:"user_id"`
	GroupID int32 `json:"group_id"`
}

func (q *Queries) RemoveStudentFromGroup(ctx context.Context, arg RemoveStudentFromGroupParams) error {
	_, err := q.db.Exec(ctx, removeStudentFromGroup, arg.UserID, arg.GroupID)
	return err
}
