// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: lessons.sql

package sqlcdb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createLesson = `-- name: CreateLesson :one
INSERT INTO lessons (group_id, title, description, scheduled_at, duration_min)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, group_id, title, description, scheduled_at, duration_min, created_at, updated_at
`

type CreateLessonParams struct {
	GroupID     int32              `json:"group_id"`
	Title       string             `json:"title"`
	Description pgtype.Text        `json:"description"`
	ScheduledAt pgtype.Timestamptz `json:"scheduled_at"`
	DurationMin int16              `json:"duration_min"`
}

func (q *Queries) CreateLesson(ctx context.Context, arg CreateLessonParams) (Lesson, error) {
	row := q.db.QueryRow(ctx, createLesson,
		arg.GroupID,
		arg.Title,
		arg.Description,
		arg.ScheduledAt,
		arg.DurationMin,
	)
	var i Lesson
	err := row.Scan(
		&i.ID,
		&i.GroupID,
		&i.Title,
		&i.Description,
		&i.ScheduledAt,
		&i.DurationMin,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteLesson = `-- name: DeleteLesson :exec
DELETE FROM lessons WHERE id = $1
`

func (q *Queries) DeleteLesson(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, deleteLesson, id)
	return err
}

const getLessonByID = `-- name: GetLessonByID :one
SELECT id, group_id, title, description, scheduled_at, duration_min, created_at, updated_at FROM lessons WHERE id = $1
`

func (q *Queries) GetLessonByID(ctx context.Context, id int32) (Lesson, error) {
	row := q.db.QueryRow(ctx, getLessonByID, id)
	var i Lesson
	err := row.Scan(
		&i.ID,
		&i.GroupID,
		&i.Title,
		&i.Description,
		&i.ScheduledAt,
		&i.DurationMin,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getLessonsByGroup = `-- name: GetLessonsByGroup :many
SELECT id, group_id, title, description, scheduled_at, duration_min, created_at, updated_at FROM lessons
WHERE group_id = $1
ORDER BY scheduled_at
LIMIT $2 OFFSET $3
`

type GetLessonsByGroupParams struct {
	GroupID int32 `json:"group_id"`
	Limit   int32 `json:"limit"`
	Offset  int32 `json:"offset"`
}

func (q *Queries) GetLessonsByGroup(ctx context.Context, arg GetLessonsByGroupParams) ([]Lesson, error) {
	rows, err := q.db.Query(ctx, getLessonsByGroup, arg.GroupID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Lesson{}
	for rows.Next() {
		var i Lesson
		if err := rows.Scan(
			&i.ID,
			&i.GroupID,
			&i.Title,
			&i.Description,
			&i.ScheduledAt,
			&i.DurationMin,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateLesson = `-- name: UpdateLesson :one
UPDATE lessons
SET title = $2, description = $3, scheduled_at = $4, duration_min = $5
WHERE id = $1
RETURNING id, group_id, title, description, scheduled_at, duration_min, created_at, updated_at
`

type UpdateLessonParams struct {
	ID          int32              `json:"id"`
	Title       string             `json:"title"`
	Description pgtype.Text        `json:"description"`
	ScheduledAt pgtype.Timestamptz `json:"scheduled_at"`
	DurationMin int16              `json:"duration_min"`
}

func (q *Queries) UpdateLesson(ctx context.Context, arg UpdateLessonParams) (Lesson, error) {
	row := q.db.QueryRow(ctx, updateLesson,
		arg.ID,
		arg.Title,
		arg.Description,
		arg.ScheduledAt,
		arg.DurationMin,
	)
	var i Lesson
	err := row.Scan(
		&i.ID,
		&i.GroupID,
		&i.Title,
		&i.Description,
		&i.ScheduledAt,
		&i.DurationMin,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
