// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcdb

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type AnswerOption struct {
	ID         int32  `json:"id"`
	QuestionID int32  `json:"question_id"`
	Text       string `json:"text"`
	IsCorrect  bool   `json:"is_correct"`
	OrderNum   int16  `json:"order_num"`
}

type BanLog struct {
	ID         int32              `json:"id"`
	UserID     int32              `json:"user_id"`
	BannedBy   int32              `json:"banned_by"`
	Reason     pgtype.Text        `json:"reason"`
	BannedAt   pgtype.Timestamptz `json:"banned_at"`
	UnbannedAt pgtype.Timestamptz `json:"unbanned_at"`
}

type EntAttempt struct {
	ID         int32              `json:"id"`
	UserID     int32              `json:"user_id"`
	Subject3ID pgtype.Int4        `json:"subject3_id"`
	Subject4ID pgtype.Int4        `json:"subject4_id"`
	StartedAt  pgtype.Timestamptz `json:"started_at"`
	FinishedAt pgtype.Timestamptz `json:"finished_at"`
	Score1     pgtype.Int2        `json:"score1"`
	Score2     pgtype.Int2        `json:"score2"`
	Score3     pgtype.Int2        `json:"score3"`
	Score4     pgtype.Int2        `json:"score4"`
}

type EntAttemptQuestion struct {
	AttemptID  int32 `json:"attempt_id"`
	QuestionID int32 `json:"question_id"`
	Slot       int16 `json:"slot"`
	OrderNum   int16 `json:"order_num"`
}

type EntSelectedOption struct {
	AttemptID  int32 `json:"attempt_id"`
	QuestionID int32 `json:"question_id"`
	OptionID   int32 `json:"option_id"`
}

type Group struct {
	ID         int32              `json:"id"`
	Name       string             `json:"name"`
	City       string             `json:"city"`
	School     string             `json:"school"`
	TeacherID  int32              `json:"teacher_id"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
	InviteCode string             `json:"invite_code"`
}

type Lesson struct {
	ID          int32              `json:"id"`
	GroupID     int32              `json:"group_id"`
	Title       string             `json:"title"`
	Description pgtype.Text        `json:"description"`
	ScheduledAt pgtype.Timestamptz `json:"scheduled_at"`
	DurationMin int16              `json:"duration_min"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type OtpCode struct {
	ID        int32              `json:"id"`
	Phone     string             `json:"phone"`
	Code      string             `json:"code"`
	Purpose   string             `json:"purpose"`
	Attempts  int16              `json:"attempts"`
	IsUsed    bool               `json:"is_used"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Question struct {
	ID          int32              `json:"id"`
	TestID      pgtype.Int4        `json:"test_id"`
	Text        string             `json:"text"`
	OrderNum    int16              `json:"order_num"`
	Points      int16              `json:"points"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	OwnerID     pgtype.Int4        `json:"owner_id"`
	TopicID     pgtype.Int4        `json:"topic_id"`
	SubtopicID  pgtype.Int4        `json:"subtopic_id"`
	Explanation pgtype.Text        `json:"explanation"`
	Difficulty  int16              `json:"difficulty"`
}

type Role struct {
	ID   int32  `json:"id"`
	Code string `json:"code"`
	Name string `json:"name"`
}

type Session struct {
	ID         int32              `json:"id"`
	UserID     int32              `json:"user_id"`
	TokenHash  string             `json:"token_hash"`
	DeviceInfo pgtype.Text        `json:"device_info"`
	Ip         pgtype.Text        `json:"ip"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	ExpiresAt  pgtype.Timestamptz `json:"expires_at"`
	RevokedAt  pgtype.Timestamptz `json:"revoked_at"`
}

type SmsLog struct {
	ID                int32              `json:"id"`
	Phone             string             `json:"phone"`
	Purpose           string             `json:"purpose"`
	Provider          string             `json:"provider"`
	Status            string             `json:"status"`
	ProviderMessageID pgtype.Text        `json:"provider_message_id"`
	SentAt            pgtype.Timestamptz `json:"sent_at"`
}

type StudentAnswer struct {
	ID         int32       `json:"id"`
	AttemptID  int32       `json:"attempt_id"`
	QuestionID int32       `json:"question_id"`
	OptionID   pgtype.Int4 `json:"option_id"`
}

type Subtopic struct {
	ID      int32  `json:"id"`
	TopicID int32  `json:"topic_id"`
	Name    string `json:"name"`
}

type Test struct {
	ID          int32              `json:"id"`
	GroupID     pgtype.Int4        `json:"group_id"`
	Title       string             `json:"title"`
	Description pgtype.Text        `json:"description"`
	TimeLimit   pgtype.Int2        `json:"time_limit"`
	MaxAttempts int16              `json:"max_attempts"`
	IsPublished bool               `json:"is_published"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
	IsPublic    bool               `json:"is_public"`
	CreatedBy   pgtype.Int4        `json:"created_by"`
	Deadline    pgtype.Timestamptz `json:"deadline"`
	TopicID     pgtype.Int4        `json:"topic_id"`
}

type TestAttempt struct {
	ID         int32              `json:"id"`
	TestID     int32              `json:"test_id"`
	UserID     int32              `json:"user_id"`
	StartedAt  pgtype.Timestamptz `json:"started_at"`
	FinishedAt pgtype.Timestamptz `json:"finished_at"`
	Score      pgtype.Int2        `json:"score"`
	MaxScore   pgtype.Int2        `json:"max_score"`
}

type TestQuestion struct {
	TestID     int32 `json:"test_id"`
	QuestionID int32 `json:"question_id"`
	OrderNum   int16 `json:"order_num"`
}

type Topic struct {
	ID   int32  `json:"id"`
	Name string `json:"name"`
}

type User struct {
	ID              int32              `json:"id"`
	Phone           string             `json:"phone"`
	FirstName       string             `json:"first_name"`
	LastName        string             `json:"last_name"`
	MiddleName      pgtype.Text        `json:"middle_name"`
	City            pgtype.Text        `json:"city"`
	RoleID          int32              `json:"role_id"`
	PasswordHash    pgtype.Text        `json:"password_hash"`
	TelegramChatID  pgtype.Int8        `json:"telegram_chat_id"`
	IsBanned        bool               `json:"is_banned"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
	ProfileSubject1 pgtype.Int4        `json:"profile_subject1"`
	ProfileSubject2 pgtype.Int4        `json:"profile_subject2"`
}

type UserGroup struct {
	ID       int32              `json:"id"`
	UserID   int32              `json:"user_id"`
	GroupID  int32              `json:"group_id"`
	JoinedAt pgtype.Timestamptz `json:"joined_at"`
}
