// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: otp.sql

package sqlcdb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createOTPCode = `-- name: CreateOTPCode :one
INSERT INTO otp_codes (phone, code, purpose, expires_at)
VALUES ($1, $2, $3, $4)
RETURNING id, phone, code, purpose, attempts, is_used, expires_at, created_at
`

type CreateOTPCodeParams struct {
	Phone     string             `json:"phone"`
	Code      string             `json:"code"`
	Purpose   string             `json:"purpose"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) CreateOTPCode(ctx context.Context, arg CreateOTPCodeParams) (OtpCode, error) {
	row := q.db.QueryRow(ctx, createOTPCode,
		arg.Phone,
		arg.Code,
		arg.Purpose,
		arg.ExpiresAt,
	)
	var i OtpCode
	err := row.Scan(
		&i.ID,
		&i.Phone,
		&i.Code,
		&i.Purpose,
		&i.Attempts,
		&i.IsUsed,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const deleteExpiredOTPCodes = `-- name: DeleteExpiredOTPCodes :exec
DELETE FROM otp_codes WHERE expires_at < NOW()
`

func (q *Queries) DeleteExpiredOTPCodes(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteExpiredOTPCodes)
	return err
}

const getActiveOTPCode = `-- name: GetActiveOTPCode :one
SELECT id, phone, code, purpose, attempts, is_used, expires_at, created_at FROM otp_codes
WHERE phone = $1
  AND purpose = $2
  AND is_used = FALSE
  AND expires_at > NOW()
ORDER BY created_at DESC
LIMIT 1
`

type GetActiveOTPCodeParams struct {
	Phone   string `json:"phone"`
	Purpose string `json:"purpose"`
}

func (q *Queries) GetActiveOTPCode(ctx context.Context, arg GetActiveOTPCodeParams) (OtpCode, error) {
	row := q.db.QueryRow(ctx, getActiveOTPCode, arg.Phone, arg.Purpose)
	var i OtpCode
	err := row.Scan(
		&i.ID,
		&i.Phone,
		&i.Code,
		&i.Purpose,
		&i.Attempts,
		&i.IsUsed,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const incrementOTPAttempts = `-- name: IncrementOTPAttempts :exec
UPDATE otp_codes SET attempts = attempts + 1 WHERE id = $1
`

func (q *Queries) IncrementOTPAttempts(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, incrementOTPAttempts, id)
	return err
}

const markOTPUsed = `-- name: MarkOTPUsed :exec
UPDATE otp_codes SET is_used = TRUE WHERE id = $1
`

func (q *Queries) MarkOTPUsed(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, markOTPUsed, id)
	return err
}
