// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcdb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	AddQuestionToTest(ctx context.Context, arg AddQuestionToTestParams) error
	AddStudentToGroup(ctx context.Context, arg AddStudentToGroupParams) (UserGroup, error)
	BanUser(ctx context.Context, id int32) error
	// ── ent_selected_options ──────────────────────────────────────────────────────
	ClearENTAnswersForQuestion(ctx context.Context, arg ClearENTAnswersForQuestionParams) error
	CountAttemptsByUserAndTest(ctx context.Context, arg CountAttemptsByUserAndTestParams) (int64, error)
	CountFinishedAttempts(ctx context.Context, testID int32) (int64, error)
	CountGroupStudents(ctx context.Context, groupID int32) (int64, error)
	CountQuestionsInTest(ctx context.Context, testID int32) (int64, error)
	CountUserGroups(ctx context.Context, userID int32) (int64, error)
	// ── answer_options ─────────────────────────────────────────────────────────
	CreateAnswerOption(ctx context.Context, arg CreateAnswerOptionParams) (AnswerOption, error)
	// ── attempts ───────────────────────────────────────────────────────────────
	CreateAttempt(ctx context.Context, arg CreateAttemptParams) (TestAttempt, error)
	// ── ent_attempts ─────────────────────────────────────────────────────────────
	CreateENTAttempt(ctx context.Context, arg CreateENTAttemptParams) (EntAttempt, error)
	CreateGroup(ctx context.Context, arg CreateGroupParams) (Group, error)
	CreateLesson(ctx context.Context, arg CreateLessonParams) (Lesson, error)
	CreateOTPCode(ctx context.Context, arg CreateOTPCodeParams) (OtpCode, error)
	// ── questions (bank) ───────────────────────────────────────────────────────
	CreateQuestion(ctx context.Context, arg CreateQuestionParams) (Question, error)
	CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error)
	CreateSubtopic(ctx context.Context, arg CreateSubtopicParams) (Subtopic, error)
	// ── tests ──────────────────────────────────────────────────────────────────
	CreateTest(ctx context.Context, arg CreateTestParams) (Test, error)
	CreateTopic(ctx context.Context, name string) (Topic, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	CreateZeroAttempt(ctx context.Context, arg CreateZeroAttemptParams) (TestAttempt, error)
	DeleteAnswerOption(ctx context.Context, id int32) error
	DeleteExpiredOTPCodes(ctx context.Context) error
	DeleteLesson(ctx context.Context, id int32) error
	DeleteQuestion(ctx context.Context, id int32) error
	DeleteTest(ctx context.Context, id int32) error
	FinishAttempt(ctx context.Context, arg FinishAttemptParams) (TestAttempt, error)
	FinishENTAttempt(ctx context.Context, arg FinishENTAttemptParams) (EntAttempt, error)
	GetActiveOTPCode(ctx context.Context, arg GetActiveOTPCodeParams) (OtpCode, error)
	GetActiveSessionsByUser(ctx context.Context, userID int32) ([]Session, error)
	GetAnswersByAttempt(ctx context.Context, attemptID int32) ([]StudentAnswer, error)
	GetAttemptByID(ctx context.Context, id int32) (TestAttempt, error)
	GetENTAttemptByID(ctx context.Context, id int32) (EntAttempt, error)
	GetENTAttemptQuestions(ctx context.Context, attemptID int32) ([]EntAttemptQuestion, error)
	GetENTSelectedOptions(ctx context.Context, attemptID int32) ([]EntSelectedOption, error)
	GetFinishedAttemptsByUser(ctx context.Context, userID int32) ([]GetFinishedAttemptsByUserRow, error)
	GetGroupByCode(ctx context.Context, inviteCode string) (Group, error)
	GetGroupByID(ctx context.Context, id int32) (Group, error)
	GetGroupByIdentity(ctx context.Context, arg GetGroupByIdentityParams) (Group, error)
	GetGroupsByTeacher(ctx context.Context, teacherID int32) ([]Group, error)
	GetGroupsByUser(ctx context.Context, userID int32) ([]Group, error)
	GetLessonByID(ctx context.Context, id int32) (Lesson, error)
	GetLessonsByGroup(ctx context.Context, arg GetLessonsByGroupParams) ([]Lesson, error)
	GetMyENTAttempts(ctx context.Context, userID int32) ([]EntAttempt, error)
	GetMyQuestions(ctx context.Context, ownerID pgtype.Int4) ([]GetMyQuestionsRow, error)
	GetMyQuestionsByTopic(ctx context.Context, arg GetMyQuestionsByTopicParams) ([]GetMyQuestionsByTopicRow, error)
	GetOptionsByQuestion(ctx context.Context, questionID int32) ([]AnswerOption, error)
	GetOptionsByTest(ctx context.Context, testID int32) ([]AnswerOption, error)
	GetPublicTests(ctx context.Context) ([]Test, error)
	GetQuestionsByTest(ctx context.Context, testID int32) ([]Question, error)
	GetRoleByID(ctx context.Context, id int32) (Role, error)
	GetSessionByID(ctx context.Context, id int32) (Session, error)
	GetStudentsByGroup(ctx context.Context, groupID int32) ([]User, error)
	GetStudentsWithoutAttempt(ctx context.Context, arg GetStudentsWithoutAttemptParams) ([]GetStudentsWithoutAttemptRow, error)
	GetSubtopicsByTopic(ctx context.Context, topicID int32) ([]Subtopic, error)
	GetTestByID(ctx context.Context, id int32) (Test, error)
	GetTestResults(ctx context.Context, testID int32) ([]GetTestResultsRow, error)
	GetTestsByCreator(ctx context.Context, createdBy pgtype.Int4) ([]Test, error)
	GetTestsByGroup(ctx context.Context, groupID pgtype.Int4) ([]Test, error)
	GetTopicByName(ctx context.Context, name string) (Topic, error)
	// ── topics ─────────────────────────────────────────────────────────────────
	GetTopics(ctx context.Context) ([]Topic, error)
	GetUserByID(ctx context.Context, id int32) (User, error)
	GetUserByPhone(ctx context.Context, phone string) (User, error)
	IncrementOTPAttempts(ctx context.Context, id int32) error
	// ── ent_attempt_questions ─────────────────────────────────────────────────────
	InsertENTQuestion(ctx context.Context, arg InsertENTQuestionParams) error
	InsertENTSelectedOption(ctx context.Context, arg InsertENTSelectedOptionParams) error
	MarkOTPUsed(ctx context.Context, id int32) error
	PublishTest(ctx context.Context, id int32) error
	RemoveQuestionFromTest(ctx context.Context, arg RemoveQuestionFromTestParams) error
	RemoveStudentFromGroup(ctx context.Context, arg RemoveStudentFromGroupParams) error
	RevokeAllUserSessions(ctx context.Context, userID int32) error
	RevokeSession(ctx context.Context, id int32) error
	UnbanUser(ctx context.Context, id int32) error
	UpdateAnswerOption(ctx context.Context, arg UpdateAnswerOptionParams) (AnswerOption, error)
	UpdateLesson(ctx context.Context, arg UpdateLessonParams) (Lesson, error)
	UpdatePassword(ctx context.Context, arg UpdatePasswordParams) error
	UpdateQuestion(ctx context.Context, arg UpdateQuestionParams) (Question, error)
	UpdateRole(ctx context.Context, arg UpdateRoleParams) error
	UpdateTelegramChatID(ctx context.Context, arg UpdateTelegramChatIDParams) error
	UpdateTest(ctx context.Context, arg UpdateTestParams) (Test, error)
	UpdateUserProfile(ctx context.Context, arg UpdateUserProfileParams) (User, error)
	// ── student_answers ────────────────────────────────────────────────────────
	UpsertStudentAnswer(ctx context.Context, arg UpsertStudentAnswerParams) (StudentAnswer, error)
}

var _ Querier = (*Queries)(nil)
