// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: sessions.sql

package sqlcdb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createSession = `-- name: CreateSession :one
INSERT INTO sessions (user_id, token_hash, device_info, ip, expires_at)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, user_id, token_hash, device_info, ip, created_at, expires_at, revoked_at
`

type CreateSessionParams struct {
	UserID     int32              `json:"user_id"`
	TokenHash  string             `json:"token_hash"`
	DeviceInfo pgtype.Text        `json:"device_info"`
	Ip         pgtype.Text        `json:"ip"`
	ExpiresAt  pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error) {
	row := q.db.QueryRow(ctx, createSession,
		arg.UserID,
		arg.TokenHash,
		arg.DeviceInfo,
		arg.Ip,
		arg.ExpiresAt,
	)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.DeviceInfo,
		&i.Ip,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.RevokedAt,
	)
	return i, err
}

const getActiveSessionsByUser = `-- name: GetActiveSessionsByUser :many
SELECT id, user_id, token_hash, device_info, ip, created_at, expires_at, revoked_at FROM sessions
WHERE user_id = $1
  AND revoked_at IS NULL
  AND expires_at > NOW()
ORDER BY created_at DESC
`

func (q *Queries) GetActiveSessionsByUser(ctx context.Context, userID int32) ([]Session, error) {
	rows, err := q.db.Query(ctx, getActiveSessionsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Session{}
	for rows.Next() {
		var i Session
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.TokenHash,
			&i.DeviceInfo,
			&i.Ip,
			&i.CreatedAt,
			&i.ExpiresAt,
			&i.RevokedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSessionByID = `-- name: GetSessionByID :one
SELECT id, user_id, token_hash, device_info, ip, created_at, expires_at, revoked_at FROM sessions WHERE id = $1
`

func (q *Queries) GetSessionByID(ctx context.Context, id int32) (Session, error) {
	row := q.db.QueryRow(ctx, getSessionByID, id)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.DeviceInfo,
		&i.Ip,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.RevokedAt,
	)
	return i, err
}

const revokeAllUserSessions = `-- name: RevokeAllUserSessions :exec
UPDATE sessions SET revoked_at = NOW()
WHERE user_id = $1 AND revoked_at IS NULL
`

func (q *Queries) RevokeAllUserSessions(ctx context.Context, userID int32) error {
	_, err := q.db.Exec(ctx, revokeAllUserSessions, userID)
	return err
}

const revokeSession = `-- name: RevokeSession :exec
UPDATE sessions SET revoked_at = NOW() WHERE id = $1
`

func (q *Queries) RevokeSession(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, revokeSession, id)
	return err
}
