// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: tests.sql

package sqlcdb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addQuestionToTest = `-- name: AddQuestionToTest :exec
INSERT INTO test_questions (test_id, question_id, order_num)
VALUES ($1, $2, $3)
ON CONFLICT (test_id, question_id) DO NOTHING
`

type AddQuestionToTestParams struct {
	TestID     int32 `json:"test_id"`
	QuestionID int32 `json:"question_id"`
	OrderNum   int16 `json:"order_num"`
}

func (q *Queries) AddQuestionToTest(ctx context.Context, arg AddQuestionToTestParams) error {
	_, err := q.db.Exec(ctx, addQuestionToTest, arg.TestID, arg.QuestionID, arg.OrderNum)
	return err
}

const countAttemptsByUserAndTest = `-- name: CountAttemptsByUserAndTest :one
SELECT COUNT(*) FROM test_attempts WHERE user_id=$1 AND test_id=$2
`

type CountAttemptsByUserAndTestParams struct {
	UserID int32 `json:"user_id"`
	TestID int32 `json:"test_id"`
}

func (q *Queries) CountAttemptsByUserAndTest(ctx context.Context, arg CountAttemptsByUserAndTestParams) (int64, error) {
	row := q.db.QueryRow(ctx, countAttemptsByUserAndTest, arg.UserID, arg.TestID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countFinishedAttempts = `-- name: CountFinishedAttempts :one
SELECT COUNT(DISTINCT user_id) FROM test_attempts WHERE test_id = $1 AND finished_at IS NOT NULL
`

func (q *Queries) CountFinishedAttempts(ctx context.Context, testID int32) (int64, error) {
	row := q.db.QueryRow(ctx, countFinishedAttempts, testID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countGroupStudents = `-- name: CountGroupStudents :one
SELECT COUNT(*) FROM user_groups WHERE group_id = $1
`

func (q *Queries) CountGroupStudents(ctx context.Context, groupID int32) (int64, error) {
	row := q.db.QueryRow(ctx, countGroupStudents, groupID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countQuestionsInTest = `-- name: CountQuestionsInTest :one
SELECT COUNT(*) FROM test_questions WHERE test_id=$1
`

func (q *Queries) CountQuestionsInTest(ctx context.Context, testID int32) (int64, error) {
	row := q.db.QueryRow(ctx, countQuestionsInTest, testID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createAnswerOption = `-- name: CreateAnswerOption :one

INSERT INTO answer_options (question_id, text, is_correct, order_num)
VALUES ($1, $2, $3, $4)
RETURNING id, question_id, text, is_correct, order_num
`

type CreateAnswerOptionParams struct {
	QuestionID int32  `json:"question_id"`
	Text       string `json:"text"`
	IsCorrect  bool   `json:"is_correct"`
	OrderNum   int16  `json:"order_num"`
}

// ── answer_options ─────────────────────────────────────────────────────────
func (q *Queries) CreateAnswerOption(ctx context.Context, arg CreateAnswerOptionParams) (AnswerOption, error) {
	row := q.db.QueryRow(ctx, createAnswerOption,
		arg.QuestionID,
		arg.Text,
		arg.IsCorrect,
		arg.OrderNum,
	)
	var i AnswerOption
	err := row.Scan(
		&i.ID,
		&i.QuestionID,
		&i.Text,
		&i.IsCorrect,
		&i.OrderNum,
	)
	return i, err
}

const createAttempt = `-- name: CreateAttempt :one

INSERT INTO test_attempts (test_id, user_id)
VALUES ($1, $2)
RETURNING id, test_id, user_id, started_at, finished_at, score, max_score
`

type CreateAttemptParams struct {
	TestID int32 `json:"test_id"`
	UserID int32 `json:"user_id"`
}

// ── attempts ───────────────────────────────────────────────────────────────
func (q *Queries) CreateAttempt(ctx context.Context, arg CreateAttemptParams) (TestAttempt, error) {
	row := q.db.QueryRow(ctx, createAttempt, arg.TestID, arg.UserID)
	var i TestAttempt
	err := row.Scan(
		&i.ID,
		&i.TestID,
		&i.UserID,
		&i.StartedAt,
		&i.FinishedAt,
		&i.Score,
		&i.MaxScore,
	)
	return i, err
}

const createQuestion = `-- name: CreateQuestion :one

INSERT INTO questions (text, order_num, points, owner_id, topic_id, subtopic_id, explanation, difficulty)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, test_id, text, order_num, points, created_at, owner_id, topic_id, subtopic_id, explanation, difficulty
`

type CreateQuestionParams struct {
	Text        string      `json:"text"`
	OrderNum    int16       `json:"order_num"`
	Points      int16       `json:"points"`
	OwnerID     pgtype.Int4 `json:"owner_id"`
	TopicID     pgtype.Int4 `json:"topic_id"`
	SubtopicID  pgtype.Int4 `json:"subtopic_id"`
	Explanation pgtype.Text `json:"explanation"`
	Difficulty  int16       `json:"difficulty"`
}

// ── questions (bank) ───────────────────────────────────────────────────────
func (q *Queries) CreateQuestion(ctx context.Context, arg CreateQuestionParams) (Question, error) {
	row := q.db.QueryRow(ctx, createQuestion,
		arg.Text,
		arg.OrderNum,
		arg.Points,
		arg.OwnerID,
		arg.TopicID,
		arg.SubtopicID,
		arg.Explanation,
		arg.Difficulty,
	)
	var i Question
	err := row.Scan(
		&i.ID,
		&i.TestID,
		&i.Text,
		&i.OrderNum,
		&i.Points,
		&i.CreatedAt,
		&i.OwnerID,
		&i.TopicID,
		&i.SubtopicID,
		&i.Explanation,
		&i.Difficulty,
	)
	return i, err
}

const createSubtopic = `-- name: CreateSubtopic :one
INSERT INTO subtopics (topic_id, name) VALUES ($1, $2)
ON CONFLICT (topic_id, name) DO UPDATE SET name = EXCLUDED.name
RETURNING id, topic_id, name
`

type CreateSubtopicParams struct {
	TopicID int32  `json:"topic_id"`
	Name    string `json:"name"`
}

func (q *Queries) CreateSubtopic(ctx context.Context, arg CreateSubtopicParams) (Subtopic, error) {
	row := q.db.QueryRow(ctx, createSubtopic, arg.TopicID, arg.Name)
	var i Subtopic
	err := row.Scan(&i.ID, &i.TopicID, &i.Name)
	return i, err
}

const createTest = `-- name: CreateTest :one

INSERT INTO tests (group_id, title, description, time_limit, max_attempts, is_public, created_by, deadline, topic_id)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, group_id, title, description, time_limit, max_attempts, is_published, created_at, updated_at, is_public, created_by, deadline, topic_id
`

type CreateTestParams struct {
	GroupID     pgtype.Int4        `json:"group_id"`
	Title       string             `json:"title"`
	Description pgtype.Text        `json:"description"`
	TimeLimit   pgtype.Int2        `json:"time_limit"`
	MaxAttempts int16              `json:"max_attempts"`
	IsPublic    bool               `json:"is_public"`
	CreatedBy   pgtype.Int4        `json:"created_by"`
	Deadline    pgtype.Timestamptz `json:"deadline"`
	TopicID     pgtype.Int4        `json:"topic_id"`
}

// ── tests ──────────────────────────────────────────────────────────────────
func (q *Queries) CreateTest(ctx context.Context, arg CreateTestParams) (Test, error) {
	row := q.db.QueryRow(ctx, createTest,
		arg.GroupID,
		arg.Title,
		arg.Description,
		arg.TimeLimit,
		arg.MaxAttempts,
		arg.IsPublic,
		arg.CreatedBy,
		arg.Deadline,
		arg.TopicID,
	)
	var i Test
	err := row.Scan(
		&i.ID,
		&i.GroupID,
		&i.Title,
		&i.Description,
		&i.TimeLimit,
		&i.MaxAttempts,
		&i.IsPublished,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IsPublic,
		&i.CreatedBy,
		&i.Deadline,
		&i.TopicID,
	)
	return i, err
}

const createTopic = `-- name: CreateTopic :one
INSERT INTO topics (name) VALUES ($1)
ON CONFLICT (name) DO UPDATE SET name = EXCLUDED.name
RETURNING id, name
`

func (q *Queries) CreateTopic(ctx context.Context, name string) (Topic, error) {
	row := q.db.QueryRow(ctx, createTopic, name)
	var i Topic
	err := row.Scan(&i.ID, &i.Name)
	return i, err
}

const createZeroAttempt = `-- name: CreateZeroAttempt :one
INSERT INTO test_attempts (test_id, user_id, started_at, finished_at, score, max_score)
VALUES ($1, $2, NOW(), NOW(), 0, $3)
ON CONFLICT DO NOTHING
RETURNING id, test_id, user_id, started_at, finished_at, score, max_score
`

type CreateZeroAttemptParams struct {
	TestID   int32       `json:"test_id"`
	UserID   int32       `json:"user_id"`
	MaxScore pgtype.Int2 `json:"max_score"`
}

func (q *Queries) CreateZeroAttempt(ctx context.Context, arg CreateZeroAttemptParams) (TestAttempt, error) {
	row := q.db.QueryRow(ctx, createZeroAttempt, arg.TestID, arg.UserID, arg.MaxScore)
	var i TestAttempt
	err := row.Scan(
		&i.ID,
		&i.TestID,
		&i.UserID,
		&i.StartedAt,
		&i.FinishedAt,
		&i.Score,
		&i.MaxScore,
	)
	return i, err
}

const deleteAnswerOption = `-- name: DeleteAnswerOption :exec
DELETE FROM answer_options WHERE id=$1
`

func (q *Queries) DeleteAnswerOption(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, deleteAnswerOption, id)
	return err
}

const deleteQuestion = `-- name: DeleteQuestion :exec
DELETE FROM questions WHERE id=$1
`

func (q *Queries) DeleteQuestion(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, deleteQuestion, id)
	return err
}

const deleteTest = `-- name: DeleteTest :exec
DELETE FROM tests WHERE id=$1
`

func (q *Queries) DeleteTest(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, deleteTest, id)
	return err
}

const finishAttempt = `-- name: FinishAttempt :one
UPDATE test_attempts SET finished_at=NOW(), score=$2, max_score=$3
WHERE id=$1 RETURNING id, test_id, user_id, started_at, finished_at, score, max_score
`

type FinishAttemptParams struct {
	ID       int32       `json:"id"`
	Score    pgtype.Int2 `json:"score"`
	MaxScore pgtype.Int2 `json:"max_score"`
}

func (q *Queries) FinishAttempt(ctx context.Context, arg FinishAttemptParams) (TestAttempt, error) {
	row := q.db.QueryRow(ctx, finishAttempt, arg.ID, arg.Score, arg.MaxScore)
	var i TestAttempt
	err := row.Scan(
		&i.ID,
		&i.TestID,
		&i.UserID,
		&i.StartedAt,
		&i.FinishedAt,
		&i.Score,
		&i.MaxScore,
	)
	return i, err
}

const getAnswersByAttempt = `-- name: GetAnswersByAttempt :many
SELECT id, attempt_id, question_id, option_id FROM student_answers WHERE attempt_id=$1
`

func (q *Queries) GetAnswersByAttempt(ctx context.Context, attemptID int32) ([]StudentAnswer, error) {
	rows, err := q.db.Query(ctx, getAnswersByAttempt, attemptID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []StudentAnswer{}
	for rows.Next() {
		var i StudentAnswer
		if err := rows.Scan(
			&i.ID,
			&i.AttemptID,
			&i.QuestionID,
			&i.OptionID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAttemptByID = `-- name: GetAttemptByID :one
SELECT id, test_id, user_id, started_at, finished_at, score, max_score FROM test_attempts WHERE id=$1
`

func (q *Queries) GetAttemptByID(ctx context.Context, id int32) (TestAttempt, error) {
	row := q.db.QueryRow(ctx, getAttemptByID, id)
	var i TestAttempt
	err := row.Scan(
		&i.ID,
		&i.TestID,
		&i.UserID,
		&i.StartedAt,
		&i.FinishedAt,
		&i.Score,
		&i.MaxScore,
	)
	return i, err
}

const getFinishedAttemptsByUser = `-- name: GetFinishedAttemptsByUser :many
SELECT ta.id, ta.test_id, t.title AS test_title,
       ta.score, ta.max_score, ta.started_at, ta.finished_at,
       t.topic_id, tp.name AS topic_name
FROM test_attempts ta
JOIN tests t ON t.id = ta.test_id
LEFT JOIN topics tp ON tp.id = t.topic_id
WHERE ta.user_id = $1 AND ta.finished_at IS NOT NULL
ORDER BY ta.finished_at DESC
`

type GetFinishedAttemptsByUserRow struct {
	ID         int32              `json:"id"`
	TestID     int32              `json:"test_id"`
	TestTitle  string             `json:"test_title"`
	Score      pgtype.Int2        `json:"score"`
	MaxScore   pgtype.Int2        `json:"max_score"`
	StartedAt  pgtype.Timestamptz `json:"started_at"`
	FinishedAt pgtype.Timestamptz `json:"finished_at"`
	TopicID    pgtype.Int4        `json:"topic_id"`
	TopicName  pgtype.Text        `json:"topic_name"`
}

func (q *Queries) GetFinishedAttemptsByUser(ctx context.Context, userID int32) ([]GetFinishedAttemptsByUserRow, error) {
	rows, err := q.db.Query(ctx, getFinishedAttemptsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetFinishedAttemptsByUserRow{}
	for rows.Next() {
		var i GetFinishedAttemptsByUserRow
		if err := rows.Scan(
			&i.ID,
			&i.TestID,
			&i.TestTitle,
			&i.Score,
			&i.MaxScore,
			&i.StartedAt,
			&i.FinishedAt,
			&i.TopicID,
			&i.TopicName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getMyQuestions = `-- name: GetMyQuestions :many
SELECT q.id, q.test_id, q.text, q.order_num, q.points, q.created_at, q.owner_id, q.topic_id, q.subtopic_id, q.explanation, q.difficulty, t.name AS topic_name, s.name AS subtopic_name
FROM questions q
LEFT JOIN topics t ON t.id = q.topic_id
LEFT JOIN subtopics s ON s.id = q.subtopic_id
WHERE q.owner_id = $1
ORDER BY q.created_at DESC
`

type GetMyQuestionsRow struct {
	ID           int32              `json:"id"`
	TestID       pgtype.Int4        `json:"test_id"`
	Text         string             `json:"text"`
	OrderNum     int16              `json:"order_num"`
	Points       int16              `json:"points"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	OwnerID      pgtype.Int4        `json:"owner_id"`
	TopicID      pgtype.Int4        `json:"topic_id"`
	SubtopicID   pgtype.Int4        `json:"subtopic_id"`
	Explanation  pgtype.Text        `json:"explanation"`
	Difficulty   int16              `json:"difficulty"`
	TopicName    pgtype.Text        `json:"topic_name"`
	SubtopicName pgtype.Text        `json:"subtopic_name"`
}

func (q *Queries) GetMyQuestions(ctx context.Context, ownerID pgtype.Int4) ([]GetMyQuestionsRow, error) {
	rows, err := q.db.Query(ctx, getMyQuestions, ownerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetMyQuestionsRow{}
	for rows.Next() {
		var i GetMyQuestionsRow
		if err := rows.Scan(
			&i.ID,
			&i.TestID,
			&i.Text,
			&i.OrderNum,
			&i.Points,
			&i.CreatedAt,
			&i.OwnerID,
			&i.TopicID,
			&i.SubtopicID,
			&i.Explanation,
			&i.Difficulty,
			&i.TopicName,
			&i.SubtopicName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getMyQuestionsByTopic = `-- name: GetMyQuestionsByTopic :many
SELECT q.id, q.test_id, q.text, q.order_num, q.points, q.created_at, q.owner_id, q.topic_id, q.subtopic_id, q.explanation, q.difficulty, t.name AS topic_name, s.name AS subtopic_name
FROM questions q
LEFT JOIN topics t ON t.id = q.topic_id
LEFT JOIN subtopics s ON s.id = q.subtopic_id
WHERE q.owner_id = $1 AND q.topic_id = $2
ORDER BY q.created_at DESC
`

type GetMyQuestionsByTopicParams struct {
	OwnerID pgtype.Int4 `json:"owner_id"`
	TopicID pgtype.Int4 `json:"topic_id"`
}

type GetMyQuestionsByTopicRow struct {
	ID           int32              `json:"id"`
	TestID       pgtype.Int4        `json:"test_id"`
	Text         string             `json:"text"`
	OrderNum     int16              `json:"order_num"`
	Points       int16              `json:"points"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	OwnerID      pgtype.Int4        `json:"owner_id"`
	TopicID      pgtype.Int4        `json:"topic_id"`
	SubtopicID   pgtype.Int4        `json:"subtopic_id"`
	Explanation  pgtype.Text        `json:"explanation"`
	Difficulty   int16              `json:"difficulty"`
	TopicName    pgtype.Text        `json:"topic_name"`
	SubtopicName pgtype.Text        `json:"subtopic_name"`
}

func (q *Queries) GetMyQuestionsByTopic(ctx context.Context, arg GetMyQuestionsByTopicParams) ([]GetMyQuestionsByTopicRow, error) {
	rows, err := q.db.Query(ctx, getMyQuestionsByTopic, arg.OwnerID, arg.TopicID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetMyQuestionsByTopicRow{}
	for rows.Next() {
		var i GetMyQuestionsByTopicRow
		if err := rows.Scan(
			&i.ID,
			&i.TestID,
			&i.Text,
			&i.OrderNum,
			&i.Points,
			&i.CreatedAt,
			&i.OwnerID,
			&i.TopicID,
			&i.SubtopicID,
			&i.Explanation,
			&i.Difficulty,
			&i.TopicName,
			&i.SubtopicName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getOptionsByQuestion = `-- name: GetOptionsByQuestion :many
SELECT id, question_id, text, is_correct, order_num FROM answer_options WHERE question_id=$1 ORDER BY order_num, id
`

func (q *Queries) GetOptionsByQuestion(ctx context.Context, questionID int32) ([]AnswerOption, error) {
	rows, err := q.db.Query(ctx, getOptionsByQuestion, questionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AnswerOption{}
	for rows.Next() {
		var i AnswerOption
		if err := rows.Scan(
			&i.ID,
			&i.QuestionID,
			&i.Text,
			&i.IsCorrect,
			&i.OrderNum,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getOptionsByTest = `-- name: GetOptionsByTest :many
SELECT ao.id, ao.question_id, ao.text, ao.is_correct, ao.order_num FROM answer_options ao
JOIN test_questions tq ON tq.question_id = ao.question_id
WHERE tq.test_id = $1
ORDER BY ao.question_id, ao.order_num, ao.id
`

func (q *Queries) GetOptionsByTest(ctx context.Context, testID int32) ([]AnswerOption, error) {
	rows, err := q.db.Query(ctx, getOptionsByTest, testID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AnswerOption{}
	for rows.Next() {
		var i AnswerOption
		if err := rows.Scan(
			&i.ID,
			&i.QuestionID,
			&i.Text,
			&i.IsCorrect,
			&i.OrderNum,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPublicTests = `-- name: GetPublicTests :many
SELECT id, group_id, title, description, time_limit, max_attempts, is_published, created_at, updated_at, is_public, created_by, deadline, topic_id FROM tests WHERE is_published = TRUE AND is_public = TRUE ORDER BY created_at DESC
`

func (q *Queries) GetPublicTests(ctx context.Context) ([]Test, error) {
	rows, err := q.db.Query(ctx, getPublicTests)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Test{}
	for rows.Next() {
		var i Test
		if err := rows.Scan(
			&i.ID,
			&i.GroupID,
			&i.Title,
			&i.Description,
			&i.TimeLimit,
			&i.MaxAttempts,
			&i.IsPublished,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.IsPublic,
			&i.CreatedBy,
			&i.Deadline,
			&i.TopicID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getQuestionsByTest = `-- name: GetQuestionsByTest :many
SELECT q.id, q.test_id, q.text, q.order_num, q.points, q.created_at, q.owner_id, q.topic_id, q.subtopic_id, q.explanation, q.difficulty FROM questions q
JOIN test_questions tq ON tq.question_id = q.id
WHERE tq.test_id = $1
ORDER BY tq.order_num, q.id
`

func (q *Queries) GetQuestionsByTest(ctx context.Context, testID int32) ([]Question, error) {
	rows, err := q.db.Query(ctx, getQuestionsByTest, testID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Question{}
	for rows.Next() {
		var i Question
		if err := rows.Scan(
			&i.ID,
			&i.TestID,
			&i.Text,
			&i.OrderNum,
			&i.Points,
			&i.CreatedAt,
			&i.OwnerID,
			&i.TopicID,
			&i.SubtopicID,
			&i.Explanation,
			&i.Difficulty,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getStudentsWithoutAttempt = `-- name: GetStudentsWithoutAttempt :many
SELECT u.id, u.first_name, u.last_name FROM users u
JOIN user_groups ug ON ug.user_id = u.id
WHERE ug.group_id = $1
  AND u.id NOT IN (
    SELECT DISTINCT user_id FROM test_attempts WHERE test_id = $2 AND finished_at IS NOT NULL
  )
`

type GetStudentsWithoutAttemptParams struct {
	GroupID int32 `json:"group_id"`
	TestID  int32 `json:"test_id"`
}

type GetStudentsWithoutAttemptRow struct {
	ID        int32  `json:"id"`
	FirstName string `json:"first_name"`
	LastName  string `json:"last_name"`
}

func (q *Queries) GetStudentsWithoutAttempt(ctx context.Context, arg GetStudentsWithoutAttemptParams) ([]GetStudentsWithoutAttemptRow, error) {
	rows, err := q.db.Query(ctx, getStudentsWithoutAttempt, arg.GroupID, arg.TestID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetStudentsWithoutAttemptRow{}
	for rows.Next() {
		var i GetStudentsWithoutAttemptRow
		if err := rows.Scan(&i.ID, &i.FirstName, &i.LastName); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSubtopicsByTopic = `-- name: GetSubtopicsByTopic :many
SELECT id, topic_id, name FROM subtopics WHERE topic_id = $1 ORDER BY name
`

func (q *Queries) GetSubtopicsByTopic(ctx context.Context, topicID int32) ([]Subtopic, error) {
	rows, err := q.db.Query(ctx, getSubtopicsByTopic, topicID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Subtopic{}
	for rows.Next() {
		var i Subtopic
		if err := rows.Scan(&i.ID, &i.TopicID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTestByID = `-- name: GetTestByID :one
SELECT id, group_id, title, description, time_limit, max_attempts, is_published, created_at, updated_at, is_public, created_by, deadline, topic_id FROM tests WHERE id = $1
`

func (q *Queries) GetTestByID(ctx context.Context, id int32) (Test, error) {
	row := q.db.QueryRow(ctx, getTestByID, id)
	var i Test
	err := row.Scan(
		&i.ID,
		&i.GroupID,
		&i.Title,
		&i.Description,
		&i.TimeLimit,
		&i.MaxAttempts,
		&i.IsPublished,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IsPublic,
		&i.CreatedBy,
		&i.Deadline,
		&i.TopicID,
	)
	return i, err
}

const getTestResults = `-- name: GetTestResults :many
SELECT u.id AS user_id, u.first_name, u.last_name,
       ta.id AS attempt_id, ta.score, ta.max_score, ta.finished_at
FROM test_attempts ta
JOIN users u ON u.id = ta.user_id
WHERE ta.test_id = $1 AND ta.finished_at IS NOT NULL
ORDER BY ta.score DESC, ta.finished_at ASC
`

type GetTestResultsRow struct {
	UserID     int32              `json:"user_id"`
	FirstName  string             `json:"first_name"`
	LastName   string             `json:"last_name"`
	AttemptID  int32              `json:"attempt_id"`
	Score      pgtype.Int2        `json:"score"`
	MaxScore   pgtype.Int2        `json:"max_score"`
	FinishedAt pgtype.Timestamptz `json:"finished_at"`
}

func (q *Queries) GetTestResults(ctx context.Context, testID int32) ([]GetTestResultsRow, error) {
	rows, err := q.db.Query(ctx, getTestResults, testID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetTestResultsRow{}
	for rows.Next() {
		var i GetTestResultsRow
		if err := rows.Scan(
			&i.UserID,
			&i.FirstName,
			&i.LastName,
			&i.AttemptID,
			&i.Score,
			&i.MaxScore,
			&i.FinishedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTestsByCreator = `-- name: GetTestsByCreator :many
SELECT id, group_id, title, description, time_limit, max_attempts, is_published, created_at, updated_at, is_public, created_by, deadline, topic_id FROM tests WHERE created_by = $1 ORDER BY created_at DESC
`

func (q *Queries) GetTestsByCreator(ctx context.Context, createdBy pgtype.Int4) ([]Test, error) {
	rows, err := q.db.Query(ctx, getTestsByCreator, createdBy)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Test{}
	for rows.Next() {
		var i Test
		if err := rows.Scan(
			&i.ID,
			&i.GroupID,
			&i.Title,
			&i.Description,
			&i.TimeLimit,
			&i.MaxAttempts,
			&i.IsPublished,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.IsPublic,
			&i.CreatedBy,
			&i.Deadline,
			&i.TopicID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTestsByGroup = `-- name: GetTestsByGroup :many
SELECT id, group_id, title, description, time_limit, max_attempts, is_published, created_at, updated_at, is_public, created_by, deadline, topic_id FROM tests WHERE group_id = $1 ORDER BY created_at DESC
`

func (q *Queries) GetTestsByGroup(ctx context.Context, groupID pgtype.Int4) ([]Test, error) {
	rows, err := q.db.Query(ctx, getTestsByGroup, groupID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Test{}
	for rows.Next() {
		var i Test
		if err := rows.Scan(
			&i.ID,
			&i.GroupID,
			&i.Title,
			&i.Description,
			&i.TimeLimit,
			&i.MaxAttempts,
			&i.IsPublished,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.IsPublic,
			&i.CreatedBy,
			&i.Deadline,
			&i.TopicID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTopicByName = `-- name: GetTopicByName :one
SELECT id, name FROM topics WHERE name = $1
`

func (q *Queries) GetTopicByName(ctx context.Context, name string) (Topic, error) {
	row := q.db.QueryRow(ctx, getTopicByName, name)
	var i Topic
	err := row.Scan(&i.ID, &i.Name)
	return i, err
}

const getTopics = `-- name: GetTopics :many

SELECT id, name FROM topics ORDER BY name
`

// ── topics ─────────────────────────────────────────────────────────────────
func (q *Queries) GetTopics(ctx context.Context) ([]Topic, error) {
	rows, err := q.db.Query(ctx, getTopics)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Topic{}
	for rows.Next() {
		var i Topic
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const publishTest = `-- name: PublishTest :exec
UPDATE tests SET is_published=TRUE WHERE id=$1
`

func (q *Queries) PublishTest(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, publishTest, id)
	return err
}

const removeQuestionFromTest = `-- name: RemoveQuestionFromTest :exec
DELETE FROM test_questions WHERE test_id=$1 AND question_id=$2
`

type RemoveQuestionFromTestParams struct {
	TestID     int32 `json:"test_id"`
	QuestionID int32 `json:"question_id"`
}

func (q *Queries) RemoveQuestionFromTest(ctx context.Context, arg RemoveQuestionFromTestParams) error {
	_, err := q.db.Exec(ctx, removeQuestionFromTest, arg.TestID, arg.QuestionID)
	return err
}

const updateAnswerOption = `-- name: UpdateAnswerOption :one
UPDATE answer_options SET text=$2, is_correct=$3, order_num=$4
WHERE id=$1 RETURNING id, question_id, text, is_correct, order_num
`

type UpdateAnswerOptionParams struct {
	ID        int32  `json:"id"`
	Text      string `json:"text"`
	IsCorrect bool   `json:"is_correct"`
	OrderNum  int16  `json:"order_num"`
}

func (q *Queries) UpdateAnswerOption(ctx context.Context, arg UpdateAnswerOptionParams) (AnswerOption, error) {
	row := q.db.QueryRow(ctx, updateAnswerOption,
		arg.ID,
		arg.Text,
		arg.IsCorrect,
		arg.OrderNum,
	)
	var i AnswerOption
	err := row.Scan(
		&i.ID,
		&i.QuestionID,
		&i.Text,
		&i.IsCorrect,
		&i.OrderNum,
	)
	return i, err
}

const updateQuestion = `-- name: UpdateQuestion :one
UPDATE questions SET text=$2, order_num=$3, points=$4, topic_id=$5, subtopic_id=$6, explanation=$7, difficulty=$8
WHERE id=$1 RETURNING id, test_id, text, order_num, points, created_at, owner_id, topic_id, subtopic_id, explanation, difficulty
`

type UpdateQuestionParams struct {
	ID          int32       `json:"id"`
	Text        string      `json:"text"`
	OrderNum    int16       `json:"order_num"`
	Points      int16       `json:"points"`
	TopicID     pgtype.Int4 `json:"topic_id"`
	SubtopicID  pgtype.Int4 `json:"subtopic_id"`
	Explanation pgtype.Text `json:"explanation"`
	Difficulty  int16       `json:"difficulty"`
}

func (q *Queries) UpdateQuestion(ctx context.Context, arg UpdateQuestionParams) (Question, error) {
	row := q.db.QueryRow(ctx, updateQuestion,
		arg.ID,
		arg.Text,
		arg.OrderNum,
		arg.Points,
		arg.TopicID,
		arg.SubtopicID,
		arg.Explanation,
		arg.Difficulty,
	)
	var i Question
	err := row.Scan(
		&i.ID,
		&i.TestID,
		&i.Text,
		&i.OrderNum,
		&i.Points,
		&i.CreatedAt,
		&i.OwnerID,
		&i.TopicID,
		&i.SubtopicID,
		&i.Explanation,
		&i.Difficulty,
	)
	return i, err
}

const updateTest = `-- name: UpdateTest :one
UPDATE tests SET title=$2, description=$3, time_limit=$4, max_attempts=$5, is_public=$6, deadline=$7, topic_id=$8
WHERE id=$1 RETURNING id, group_id, title, description, time_limit, max_attempts, is_published, created_at, updated_at, is_public, created_by, deadline, topic_id
`

type UpdateTestParams struct {
	ID          int32              `json:"id"`
	Title       string             `json:"title"`
	Description pgtype.Text        `json:"description"`
	TimeLimit   pgtype.Int2        `json:"time_limit"`
	MaxAttempts int16              `json:"max_attempts"`
	IsPublic    bool               `json:"is_public"`
	Deadline    pgtype.Timestamptz `json:"deadline"`
	TopicID     pgtype.Int4        `json:"topic_id"`
}

func (q *Queries) UpdateTest(ctx context.Context, arg UpdateTestParams) (Test, error) {
	row := q.db.QueryRow(ctx, updateTest,
		arg.ID,
		arg.Title,
		arg.Description,
		arg.TimeLimit,
		arg.MaxAttempts,
		arg.IsPublic,
		arg.Deadline,
		arg.TopicID,
	)
	var i Test
	err := row.Scan(
		&i.ID,
		&i.GroupID,
		&i.Title,
		&i.Description,
		&i.TimeLimit,
		&i.MaxAttempts,
		&i.IsPublished,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IsPublic,
		&i.CreatedBy,
		&i.Deadline,
		&i.TopicID,
	)
	return i, err
}

const upsertStudentAnswer = `-- name: UpsertStudentAnswer :one

INSERT INTO student_answers (attempt_id, question_id, option_id)
VALUES ($1, $2, $3)
ON CONFLICT (attempt_id, question_id) DO UPDATE SET option_id = EXCLUDED.option_id
RETURNING id, attempt_id, question_id, option_id
`

type UpsertStudentAnswerParams struct {
	AttemptID  int32       `json:"attempt_id"`
	QuestionID int32       `json:"question_id"`
	OptionID   pgtype.Int4 `json:"option_id"`
}

// ── student_answers ────────────────────────────────────────────────────────
func (q *Queries) UpsertStudentAnswer(ctx context.Context, arg UpsertStudentAnswerParams) (StudentAnswer, error) {
	row := q.db.QueryRow(ctx, upsertStudentAnswer, arg.AttemptID, arg.QuestionID, arg.OptionID)
	var i StudentAnswer
	err := row.Scan(
		&i.ID,
		&i.AttemptID,
		&i.QuestionID,
		&i.OptionID,
	)
	return i, err
}
