// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package sqlcdb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const banUser = `-- name: BanUser :exec
UPDATE users SET is_banned = TRUE WHERE id = $1
`

func (q *Queries) BanUser(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, banUser, id)
	return err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (phone, first_name, last_name, middle_name, city, role_id)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, phone, first_name, last_name, middle_name, city, role_id, password_hash, telegram_chat_id, is_banned, created_at, updated_at, profile_subject1, profile_subject2
`

type CreateUserParams struct {
	Phone      string      `json:"phone"`
	FirstName  string      `json:"first_name"`
	LastName   string      `json:"last_name"`
	MiddleName pgtype.Text `json:"middle_name"`
	City       pgtype.Text `json:"city"`
	RoleID     int32       `json:"role_id"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.Phone,
		arg.FirstName,
		arg.LastName,
		arg.MiddleName,
		arg.City,
		arg.RoleID,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Phone,
		&i.FirstName,
		&i.LastName,
		&i.MiddleName,
		&i.City,
		&i.RoleID,
		&i.PasswordHash,
		&i.TelegramChatID,
		&i.IsBanned,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ProfileSubject1,
		&i.ProfileSubject2,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, phone, first_name, last_name, middle_name, city, role_id, password_hash, telegram_chat_id, is_banned, created_at, updated_at, profile_subject1, profile_subject2 FROM users WHERE id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id int32) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Phone,
		&i.FirstName,
		&i.LastName,
		&i.MiddleName,
		&i.City,
		&i.RoleID,
		&i.PasswordHash,
		&i.TelegramChatID,
		&i.IsBanned,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ProfileSubject1,
		&i.ProfileSubject2,
	)
	return i, err
}

const getUserByPhone = `-- name: GetUserByPhone :one
SELECT id, phone, first_name, last_name, middle_name, city, role_id, password_hash, telegram_chat_id, is_banned, created_at, updated_at, profile_subject1, profile_subject2 FROM users WHERE phone = $1
`

func (q *Queries) GetUserByPhone(ctx context.Context, phone string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByPhone, phone)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Phone,
		&i.FirstName,
		&i.LastName,
		&i.MiddleName,
		&i.City,
		&i.RoleID,
		&i.PasswordHash,
		&i.TelegramChatID,
		&i.IsBanned,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ProfileSubject1,
		&i.ProfileSubject2,
	)
	return i, err
}

const unbanUser = `-- name: UnbanUser :exec
UPDATE users SET is_banned = FALSE WHERE id = $1
`

func (q *Queries) UnbanUser(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, unbanUser, id)
	return err
}

const updatePassword = `-- name: UpdatePassword :exec
UPDATE users SET password_hash = $2 WHERE id = $1
`

type UpdatePasswordParams struct {
	ID           int32       `json:"id"`
	PasswordHash pgtype.Text `json:"password_hash"`
}

func (q *Queries) UpdatePassword(ctx context.Context, arg UpdatePasswordParams) error {
	_, err := q.db.Exec(ctx, updatePassword, arg.ID, arg.PasswordHash)
	return err
}

const updateRole = `-- name: UpdateRole :exec
UPDATE users SET role_id = $2 WHERE id = $1
`

type UpdateRoleParams struct {
	ID     int32 `json:"id"`
	RoleID int32 `json:"role_id"`
}

func (q *Queries) UpdateRole(ctx context.Context, arg UpdateRoleParams) error {
	_, err := q.db.Exec(ctx, updateRole, arg.ID, arg.RoleID)
	return err
}

const updateTelegramChatID = `-- name: UpdateTelegramChatID :exec
UPDATE users SET telegram_chat_id = $2 WHERE id = $1
`

type UpdateTelegramChatIDParams struct {
	ID             int32       `json:"id"`
	TelegramChatID pgtype.Int8 `json:"telegram_chat_id"`
}

func (q *Queries) UpdateTelegramChatID(ctx context.Context, arg UpdateTelegramChatIDParams) error {
	_, err := q.db.Exec(ctx, updateTelegramChatID, arg.ID, arg.TelegramChatID)
	return err
}

const updateUserProfile = `-- name: UpdateUserProfile :one
UPDATE users
SET first_name = $2, last_name = $3, middle_name = $4, city = $5,
    profile_subject1 = $6, profile_subject2 = $7
WHERE id = $1
RETURNING id, phone, first_name, last_name, middle_name, city, role_id, password_hash, telegram_chat_id, is_banned, created_at, updated_at, profile_subject1, profile_subject2
`

type UpdateUserProfileParams struct {
	ID              int32       `json:"id"`
	FirstName       string      `json:"first_name"`
	LastName        string      `json:"last_name"`
	MiddleName      pgtype.Text `json:"middle_name"`
	City            pgtype.Text `json:"city"`
	ProfileSubject1 pgtype.Int4 `json:"profile_subject1"`
	ProfileSubject2 pgtype.Int4 `json:"profile_subject2"`
}

func (q *Queries) UpdateUserProfile(ctx context.Context, arg UpdateUserProfileParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUserProfile,
		arg.ID,
		arg.FirstName,
		arg.LastName,
		arg.MiddleName,
		arg.City,
		arg.ProfileSubject1,
		arg.ProfileSubject2,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Phone,
		&i.FirstName,
		&i.LastName,
		&i.MiddleName,
		&i.City,
		&i.RoleID,
		&i.PasswordHash,
		&i.TelegramChatID,
		&i.IsBanned,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ProfileSubject1,
		&i.ProfileSubject2,
	)
	return i, err
}
